### PR TITLE
Replace go-bindata with standard go:embed

### PR DESCRIPTION
**Pull request by lpar**
This removes the use of go-bindata for the SQL schema files, in favor of standard go:embed.

---

- [X] I have signed the [CLA](https://phabricator.write.as/L1)

### CODE REVIEW

**Comment by thebaer** [comment]
Looks great. Thank you for tackling this! Will merge now.

**Review by thebaer — APPROVED** [review]

**Comment by gytisrepecka** [comment]
I have a feeling this change causes building on `develop` branch to fail as of now:

```bash
$ make build
go get -tags='sqlite' -d -v ./...
cd cmd/writefreely; go build -ldflags="-s -w -X 'github.com/writefreely/writefreely.softwareVer=`git describe | cut -c 2-`'" -v -tags='netgo sqlite'
github.com/writefreely/writefreely
# github.com/writefreely/writefreely
../../bindata.go:34:6: schemaSql redeclared in this block
        ../../app.go:928:5: other declaration of schemaSql
../../bindata.go:52:6: sqliteSql redeclared in this block
        ../../app.go:931:5: other declaration of sqliteSql
../../bindata.go:121:16: cannot use schemaSql (variable of type string) as type func() (*asset, error) in map literal
../../bindata.go:122:16: cannot use sqliteSql (variable of type string) as type func() (*asset, error) in map literal
../../bindata.go:165:25: cannot use schemaSql (variable of type string) as type func() (*asset, error) in struct literal
../../bindata.go:166:25: cannot use sqliteSql (variable of type string) as type func() (*asset, error) in struct literal
make: *** [build] Error 2
```

**Comment by lpar** [comment]
@gytisrepecka You shouldn't have a `bindata.go` file any more, it was a file generated by the old go-bindata system. You can just delete it, it's in `.gitignore` and isn't part of the project.

**Comment by gytisrepecka** [comment]
Thanks, removing `bindata.go` solves the issue and WriteFreely build from `develop` now succeeds 👍

**Comment by prologic** [comment]
I just cloned the this repo and tried to run `make build` and this is still using `go-bindata` hmmm

```
prologic@JamessMacStudio
Sun Feb 11 17:01:27
~/Contributions/writefreely
 (develop) 0
$ make build
go: downloading github.com/jteeuwen/go-bindata v3.0.7+incompatible
go: added github.com/jteeuwen/go-bindata v3.0.7+incompatible
go-bindata -pkg writefreely -ignore=\\.gitignore -tags="!wflib" schema.sql sqlite.sql
/bin/sh: go-bindata: command not found
make: *** [assets] Error 127

prologic@JamessMacStudio
Sun Feb 11 17:01:34
~/Contributions/writefreely
 (develop) 2
$ git id
b7f732b
```

**Comment by prologic** [comment]
Ahh ooops, looks like I forgot I had a clone from years ago 🤦‍♂️

**Pull request merged**
