### PR TITLE
Add pagination to tag subpages

### LINKED ISSUE #362: Tag subpages do not paginate
### Describe the bug

When you have a tag with more than 10 posts, the tag subpage only shows the latest 10 and not the rest of these posts.

### Expected behavior

There should be a "Older" or "Next" button on the button for the next page of tagged posts.

### PR DESCRIPTION
**Pull request by Dak425**
Fixes #362 

---

- [ x ] I have signed the [CLA](https://phabricator.write.as/L1)

### CODE REVIEW

**Review by thebaer — CHANGES_REQUESTED** [review]
Thanks for submitting this fix! Sorry it's taken so long to review this.

It looks like this does add most of what we need for pagination, but it also always shows the "Older" link on tag pages, even when there aren't more pages to go to. We'll need to fix that before merging.

**Comment by Dak425** [comment]
> Thanks for submitting this fix! Sorry it's taken so long to review this.
> 
> It looks like this does add most of what we need for pagination, but it also always shows the "Older" link on tag pages, even when there aren't more pages to go to. We'll need to fix that before merging.

Ah gotcha missed that. Will fix soon

**Comment by thebaer** [comment]
Hey @Dak425, any update on this?

**Comment by Dak425** [comment]
Sorry I have not had time to, someone else can finish it up if they
would like to

**Comment by mlo-3** [comment]
Hello, thank you the work done. Anyone willing to finish the task so that the pagination will be done ?
 
This is really too bad that the tag page can not make visible all the posts with that tag but only the last 10 :/

Thank you ! :)

**Comment by thebaer** [comment]
Patched this up, but only tested with MySQL and multi-user instance. Need to confirm it works with SQLite and single-user blogs, then we can merge.

**Comment by thebaer** [comment]
Looks good! Merging now.

**Pull request merged**
