### PR TITLE
fix: RTL support on post textarea

### LINKED ISSUE #612: Editor Screen Doesn't Support Bidirectional Texts
### Describe the bug
When I'm writing in an RTL language at the editor screen, text direction is not set to RTL. But it has no problems with LTR languages. In other words, the user is expecting the text field to support bidirectional texts, but it doesn't. 

### Steps to reproduce (if necessary)
1. Go to the editor screen
2. Start typing in an RTL language (Persian, Arabic, etc.), followed by some LTR Paragraph.
3. You'll see something like this, which is disturbing.
image

### Expected behavior
image
Adding bidi support is very easy, I assume. I just attached `dir="auto"` to the `textarea`. (Maybe there are some other places you should use this attribute. I don't know.)

### Applications configuration
 - Multi-user Mode
 - Open Registration
 - Federation Enabled

v0.13.1

### PR DESCRIPTION
**Pull request by andi1984**
Fixing right to left (short: RTL) support for respective RTL languages by adding auto-detection for the user content's directionality based on the text's language.

Fixes #612

---

- [x] I have signed the [CLA](https://phabricator.write.as/L1)

### CODE REVIEW

**Comment by andi1984** [comment]
@thebaer Sorry, VSCode was thinking to format a bit the document 😮‍💨. If it is an issue, I can revert those non-issue related formatting changes.

**Comment by thebaer** [comment]
Thanks for submitting this! Yes, please revert those formatting changes unrelated to this issue, and I'll get this merged.

**Comment by andi1984** [comment]
@thebaer sure, just updated it.

**Comment by thebaer** [comment]
Thanks! Merging this now.

**Pull request merged**
