### PR TITLE
#514 - Fix login with Gitea OAuth: external user ID not recorded

### PR DESCRIPTION
**Pull request by gytisrepecka**
Fix issue #514 - fix details:

* change inspect endpoint, add missing fields to receive scope, external user ID, username, display name and email;
* change error message when OAuth account is already associated;
* log external (Gitea) user ID in addition to internal (WriteFreely) user ID;
* include additional auth fields into `oauth_gitea.go` based on `oauth_generic.go`.

---

- [x] I have signed the [CLA](https://phabricator.write.as/L1)

### CODE REVIEW

**Comment by gytisrepecka** [comment]
Running successfully in production for a while now. Anyone could test it as well?

**Comment by gytisrepecka** [comment]
> Thanks for addressing this, @gytisrepecka!
> 
> This looks good from reading through, but I have just one concern: in what Gitea version did the inspect endpoint change? I'm thinking this might break current integrations, and we'll probably want to document this somewhere so people are aware.

I believe I used wrong inspect endpoint from the beginning: in [Gitea OAuth2 provider documentation](https://docs.gitea.io/en-us/oauth2-provider/) **OpenID Connect UserInfo** is specified as `/login/oauth/userinfo`.

OAuth provider functionality is available in Gitea since v1.8.0 and it seems real endpoint did not change over time - it was simply [not specified](https://github.com/go-gitea/gitea/commit/29695cd6d511823ab0d233bba8c7971e5dac3e5f#diff-e92fdc50af1f3b627325df503decfef6204e717f30fee35bda9e625e50afcedf) in documentation, therefore I took [whatever I was able to find from API](https://gitea.com/api/swagger#/user/userGetCurrent).

**Comment by thebaer** [comment]
Ah, okay great -- that makes sense!

**Review by thebaer — APPROVED** [review]
Since it's been working in production for a while, and code looks good, this is good to go :+1:

**Pull request merged**
